import { ReactNode, useEffect } from "react"
import Head from "next/head"
import MyHeader from "./composite/myheader"
import MyHeaderMobile from "./composite/myheadermobile"
import Footer from "./composite/footer"
import { useDispatch } from "react-redux"
import { getUser } from "@/store/loginUserSlice"
import { AppDispatch } from "@/store/store"

interface LayoutProps {
    children: ReactNode,
    title: string,
}

const Layout: React.FC<LayoutProps> = ({ children, title }) => {
    const dispatch : AppDispatch = useDispatch();

    useEffect( () => {
        dispatch(getUser());
    }, [dispatch]);

    return (
        <>
        <div className="layout-container d-flex flex-column flex-fill">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/ico/page_ico.png" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
            </Head>

            <MyHeader className="d-none d-md-block" />
            <MyHeaderMobile className="d-md-none" />
            {children}
            <div className="flex-fill"> </div>
            <Footer />
        </div>
        </>
    )
}

export default Layout;