import { ReactNode } from "react"
import Head from "next/head"
import MyHeader from "./myheader"
import MyHeaderMobile from "./myheadermobile"
import Footer from "./footer"

interface LayoutProps {
    children: ReactNode,
    title: string,
}

const Layout: React.FC<LayoutProps> = ({ children, title }) => {
    return (
        <>
        <div className="layout-container d-flex flex-column flex-fill">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/ico/page_ico.png" />
            </Head>

            <MyHeader className="d-none d-md-block" />
            <MyHeaderMobile className="d-md-none" />
            {children}
            <div className="flex-fill"> </div>
            <Footer />
        </div>
        </>
    )
}

export default Layout;