import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useForm } from 'react-hook-form'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { register, handleSubmit, formState: {errors}} = useForm()

  const onSubmit = ( data : any ) => console.log(data)
  const emailRegists = register("email", {
    required : {
      value: true,
      message: "入力が必須の項目です",
    },
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Test Page</h1>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div>
            <label htmlFor="email">Email</label>
            <input id="email" {...emailRegists} />
            { errors.email && <div>必須の項目です</div>}
          </div>
          <button type="submit">Submit</button>
        </form>
      </div>
    </>
  )
}
